/*
 * This file is generated by jOOQ.
*/
package com.alekseysamoylov.db.transaction;


import com.alekseysamoylov.db.transaction.tables.Product;
import com.alekseysamoylov.db.transaction.tables.Store;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index PRODUCT_PKEY = Indexes0.PRODUCT_PKEY;
    public static final Index STORE_PKEY = Indexes0.STORE_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index PRODUCT_PKEY = Internal.createIndex("product_pkey", Product.PRODUCT, new OrderField[] { Product.PRODUCT.ID }, true);
        public static Index STORE_PKEY = Internal.createIndex("store_pkey", Store.STORE, new OrderField[] { Store.STORE.ID }, true);
    }
}
