/*
 * This file is generated by jOOQ.
*/
package com.alekseysamoylov.db.transaction;


import com.alekseysamoylov.db.transaction.tables.Product;
import com.alekseysamoylov.db.transaction.tables.Store;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1406191458;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.product</code>.
     */
    public final Product PRODUCT = com.alekseysamoylov.db.transaction.tables.Product.PRODUCT;

    /**
     * The table <code>public.store</code>.
     */
    public final Store STORE = com.alekseysamoylov.db.transaction.tables.Store.STORE;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Product.PRODUCT,
            Store.STORE);
    }
}
