/*
 * This file is generated by jOOQ.
*/
package com.alekseysamoylov.db.transaction;


import com.alekseysamoylov.db.transaction.tables.Product;
import com.alekseysamoylov.db.transaction.tables.Store;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.product</code>.
     */
    public static final Product PRODUCT = com.alekseysamoylov.db.transaction.tables.Product.PRODUCT;

    /**
     * The table <code>public.store</code>.
     */
    public static final Store STORE = com.alekseysamoylov.db.transaction.tables.Store.STORE;
}
