version: '3'
services:
  postgres:
    image: library/postgres:9.6.8
    volumes:
    - ./init_db.sql:/docker-entrypoint-initdb.d/1-init.sql
    ports:
    - "5432:5432"
    restart: unless-stopped
    # it can be deleted
    environment:
    - DB_USER=db_user
    - DB_PASS=sql
